{
 "title": "Capture History",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Ladle : Temporature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  t0 as value,\n  \"t0\" as metric\nFROM t_ladle_capture\nWHERE $__timeFilter(time)\nORDER BY time ASC\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  t1 as value,\n  \"t1\" as metric\nFROM t_ladle_capture\nWHERE $__timeFilter(time)\nORDER BY time ASC\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  t2 as value,\n  \"t2\" as metric\nFROM t_ladle_capture\nWHERE $__timeFilter(time)\nORDER BY time ASC\n"
    },
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  t1 as value,\n  \"t1\" as metric\nFROM t_ladle_capture\nWHERE $__timeFilter(time)\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "KR : Distance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(time) as time_sec,\n  distance as value,\n  \"distamce\" as metric\nFROM t_kr_capture\nWHERE $__timeFilter(time)\nORDER BY time ASC\n"
    }
   ]
  },
  {
   "title": "KR : Captured Image History",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT time, fileName as FILE, distance as CM, sno as SENSOR FROM t_kr_capture LIMIT 2000;"
    }
   ]
  }
 ]
}